feat: Реализовать сервис для работы с крипто про плагином
kaluga-astral/cryptopro-cades pull request #1
Opened 2022-05-13 12:27 UTC by mt89vein

2022-05-13 13:24 UTC, AndTem commented
Добавь в название ПРИВЕТ scope - feat(cryptopro-cades): message

2022-05-13 13:28 UTC, AndTem requested changes

2022-05-13 13:28 UTC, AndTem commented on package.json
> +    "asn1js": "^3.0.2"
эта либа не нужна в корневом package.json

2022-05-13 13:28 UTC, AndTem commented on packages/cryptopro-cades/src/index.ts
> +export * from './errors/index';
index указывать не нужно

2022-05-13 13:38 UTC, mt89vein commented on packages/cryptopro-cades/src/index.ts
> +export * from './errors/index';
линтер иногда тупит и ругается без него ) уберу

2022-05-16 06:25 UTC, mt89vein commented on package.json
> +    "asn1js": "^3.0.2"
да, я её удалил - npm не туда установил

2022-05-16 08:15 UTC, merged