feat(cryptopro-cades): Доработать парсинг атрибутов сертификатов, добавлен отладочный вывод для всех основных функций, улучшена песочница.
kaluga-astral/cryptopro-cades pull request #15
Opened 2022-05-24 15:39 UTC by mt89vein

2022-05-24 16:24 UTC, StanislavDa approved these changes

2022-05-25 05:47 UTC, AndTem requested changes

2022-05-25 05:47 UTC, AndTem commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
все должно импортиться из корня, без /types

2022-05-25 05:47 UTC, AndTem commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src';
Все должно работать и без src. За это отвечают поля в package: browser и types

2022-05-25 05:49 UTC, mt89vein commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
локально не работает, не находит типы

2022-05-25 05:50 UTC, mt89vein commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
![image](https://user-images.githubusercontent.com/13538500/170189327-afddaf9f-1de4-4b43-88e3-f9d707eddd0d.png)

2022-05-25 06:24 UTC, AndTem commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
@mt89vein потому, что у тебя в packages.json свойство types указывает на файл, которого не существует (локально)
<img width="261" alt="image" src="https://user-images.githubusercontent.com/23665108/170194357-ae1ce230-6379-432d-8854-4cd72a7c0b06.png">

2022-05-25 06:37 UTC, mt89vein commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
я пробовал туда указывать и index.ts, ничего не меняется :) и даже если указывать не относительный путь

2022-05-25 08:50 UTC, mt89vein commented on examples/cryptopro-cades/src/App.tsx
> +} from '@astral/cryptopro-cades/src/types';
готово. конвертировал все типы которые нужны во вне из d.ts в ts

2022-05-25 09:05 UTC, AndTem approved these changes

2022-05-25 09:06 UTC, merged