feat(cryptopro-cades): Добавил поддержку "сырой" подписи хэша
kaluga-astral/cryptopro-cades pull request #51
Opened 2024-05-22 00:51 UTC by va4es2

Добавил поддержку "сырой" подписи хэша - функция signHashRaw - возвращает подпись хэша в формате Hex строки.

2024-06-05 15:05 UTC, aiekseu requested changes

2024-06-05 15:05 UTC, aiekseu commented on packages/cryptopro-cades/src/types/cadesplugin/RawSignature.ts
> +export type RawSignature = {
Рядом уже лежит такой интерфейс, IRawSignature, нигде не используется. 

Если принципиально нужен тип, то ок. В любом случае, удали лишний

2024-06-05 15:05 UTC, aiekseu commented on packages/cryptopro-cades/src/api/signHashRaw.ts
> +export function signHashRaw(
Метод почти полностью совпадает с `signHash`. Может быть просто расширить тот? 

Функцию оставить для прозрачности, а в ней вызвать `signHash` с нужными параметрами

2024-06-05 18:04 UTC, va4es2 commented on packages/cryptopro-cades/src/types/cadesplugin/RawSignature.ts
> +export type RawSignature = {
нужны оба

2024-06-05 18:05 UTC, va4es2 commented on packages/cryptopro-cades/src/api/signHashRaw.ts
> +export function signHashRaw(
Это совершенно другой метод.
Тот создает обычный CMS файл подписи, а этот просто 32 байта "сырой" подписи

2024-06-06 07:38 UTC, aiekseu commented on packages/cryptopro-cades/src/api/signHashRaw.ts
> +      const signer: CPSigner = await createObject(CRYPTO_OBJECTS.signer);
Ок, поправь то что линтер говорит и можно вливать

2024-06-11 06:21 UTC, va4es2 commented on packages/cryptopro-cades/src/api/signHashRaw.ts
> +      const signer: CPSigner = await createObject(CRYPTO_OBJECTS.signer);
убрал лишнее

2024-06-11 07:06 UTC, aiekseu approved these changes

2024-06-11 07:08 UTC, AndTem approved these changes

2024-06-11 07:08 UTC, merged